default:
  image: node:14.17.0-alpine # Updated node version
  tags:
    - deploy

stages:
  - scan
  - build
  - test

.default-refs: &default-refs
  refs:
    - main
    - dev
    - merge_requests

.only-default: &only-default
  only:
    <<: *default-refs

.web-install: &web-install
  before_script:
    - npm install --global @angular/cli
    - npm install

.web-cache: &web-cache
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build-web:
  stage: build
  image: node:16-alpine # Updated to node version 16
  <<: *only-default
  <<: *web-install
  script:
    - ng build
  <<: *web-cache
  artifacts:
    expire_in: 30 days
    expose_as: "web"
    paths:
      - ./dist

.lint-web:
  stage: test
  image: node:16-alpine # Updated to node version 16
  <<: *only-default
  needs:
    - build-web
  allow_failure: true
  <<: *web-install
  script:
    - ng lint
  <<: *web-cache
