export enum RolesEnum {
  ROLE_DEVELOPER = 'ROLE_DEVELOPER',
  ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ROLE_RM_INVENTORY = 'ROLE_RM_INVENTORY',
  ROLE_DESIGNER = 'ROLE_DESIGNER',
  ROLE_MERCHANDISER = 'ROLE_MERCHANDISER',
  ROLE_INVENTORY_FG = "ROLE_INVENTORY_FG",
  ROLE_MARKETING = "ROLE_MARKETING",
  ROLE_INVENTORY_ADMIN = "ROLE_INVENTORY_ADMIN"
}
